
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv-container
        image: ichrakyhy/cv-onepage:latest
        ports:
        - containerPort: 80
