
# roles/update/tasks/main.yml
---
- name: Mettre à jour le cache APT (ignorer les erreurs GPG)
  command: apt-get update
  changed_when: false
  ignore_errors: yes

- name: Mettre à jour tous les paquets
  apt:
    upgrade: dist
    state: latest
