
---
- name: Installer unzip
  apt:
    name: unzip
    state: present
    # Supprimer update_cache: yes pour éviter l'erreur

- name: Télécharger Terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    dest: /tmp/terraform.zip
    mode: '0644'

- name: Décompresser Terraform dans /usr/local/bin
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
